// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace US.AcceptanceTests.Features.Login
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class LoginFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Login.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Login", "    In order to check the login", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Login")))
            {
                global::US.AcceptanceTests.Features.Login.LoginFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("This is a generic feature using a failed login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.OwnerAttribute("sernajaj")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Story:Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InternalTcId:0AAA31D0-AD03-4180-94D2-E93148047844")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CreationDate:2018-04-14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ReviewDate:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Reviewer:")]
        public virtual void ThisIsAGenericFeatureUsingAFailedLogin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("This is a generic feature using a failed login", new string[] {
                        "Story:Login",
                        "InternalTcId:0AAA31D0-AD03-4180-94D2-E93148047844",
                        "Owner:sernajaj",
                        "CreationDate:2018-04-14",
                        "ReviewDate:",
                        "Reviewer:"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("The user goes to the \'http://demo.guru99.com/v4/index.php\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserId",
                        "Password"});
            table1.AddRow(new string[] {
                        "fakeUser",
                        "fakePassword"});
#line 12
 testRunner.When("The user tries to login with the following user", ((string)(null)), table1, "When ");
#line 15
 testRunner.Then("The user cannot login and the \'User or Password is not valid\' alert appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("This is another generic feature using a failed login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.OwnerAttribute("sernajaj")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Story:Login")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("InternalTcId:81C2740C-13E8-4A66-B820-ADEA68EE9B86")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CreationDate:2018-04-14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ReviewDate:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Reviewer:")]
        public virtual void ThisIsAnotherGenericFeatureUsingAFailedLogin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("This is another generic feature using a failed login", new string[] {
                        "Story:Login",
                        "InternalTcId:81C2740C-13E8-4A66-B820-ADEA68EE9B86",
                        "Owner:sernajaj",
                        "CreationDate:2018-04-14",
                        "ReviewDate:",
                        "Reviewer:"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("The user goes to the \'http://demo.guru99.com/v4/index.php\' page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.When("The user \'anotherUser\' login to the web page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("The user cannot login and the \'User or Password is not valid\' alert appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
